#!/bin/bash
./main < testes3_semBrodcast/1.in > testes3_semBrodcast/resultado3_semBroadcast/1.out &
./main < testes3_semBrodcast/2.in > testes3_semBrodcast/resultado3_semBroadcast/2.out &
./main < testes3_semBrodcast/3.in > testes3_semBrodcast/resultado3_semBroadcast/3.out &
./main < testes3_semBrodcast/4.in > testes3_semBrodcast/resultado3_semBroadcast/4.out &
./main < testes3_semBrodcast/5.in > testes3_semBrodcast/resultado3_semBroadcast/5.out &
./main < testes3_semBrodcast/6.in > testes3_semBrodcast/resultado3_semBroadcast/6.out &
./main < testes3_semBrodcast/7.in > testes3_semBrodcast/resultado3_semBroadcast/7.out &
./main < testes3_semBrodcast/8.in > testes3_semBrodcast/resultado3_semBroadcast/8.out &
./main < testes3_semBrodcast/9.in > testes3_semBrodcast/resultado3_semBroadcast/9.out &
./main < testes3_semBrodcast/10.in > testes3_semBrodcast/resultado3_semBroadcast/10.out &