#!/bin/bash
./main < testes4/1.in > testes4/resultado4/1.out &
./main < testes4/2.in > testes4/resultado4/2.out &
./main < testes4/3.in > testes4/resultado4/3.out &
./main < testes4/4.in > testes4/resultado4/4.out &
./main < testes4/5.in > testes4/resultado4/5.out &
./main < testes4/6.in > testes4/resultado4/6.out &
./main < testes4/7.in > testes4/resultado4/7.out &
./main < testes4/8.in > testes4/resultado4/8.out &
./main < testes4/9.in > testes4/resultado4/9.out &
./main < testes4/10.in > testes4/resultado4/10.out &